dist: xenial

addons:
  postgresql: 9.6
  # TODO: Add mysql addon as well

services:
  - postgresql
  - redis-server

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true

cache:
  - pip


env:
  global:
    - POSTGRESQL_SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
    - ES6_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.0.tar.gz"
    - ES7_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-linux-x86_64.tar.gz"
    - ES_HOST=127.0.0.1
  matrix:
    - REQUIREMENTS=release OAREPO_VERSION=3.1.1 ES=$ES6_DOWNLOAD_URL EXTRAS=postgresql,tests SQLALCHEMY_DATABASE_URI=$POSTGRESQL_SQLALCHEMY_DATABASE_URI
    - REQUIREMENTS=release OAREPO_VERSION=3.2.0 ES=$ES6_DOWNLOAD_URL EXTRAS=postgresql,tests SQLALCHEMY_DATABASE_URI=$POSTGRESQL_SQLALCHEMY_DATABASE_URI
    - REQUIREMENTS=release OAREPO_VERSION=3.2.0 ES=$ES6_DOWNLOAD_URL EXTRAS=sqlite,tests
    - REQUIREMENTS=release OAREPO_VERSION=3.2.0 ES=$ES7_DOWNLOAD_URL EXTRAS=postgresql,tests-es7 SQLALCHEMY_DATABASE_URI=$POSTGRESQL_SQLALCHEMY_DATABASE_URI
    - REQUIREMENTS=release OAREPO_VERSION=3.2.0 ES=$ES7_DOWNLOAD_URL EXTRAS=sqlite,tests-es7
    - REQUIREMENTS=release OAREPO_VERSION=3.2.1 ES=$ES7_DOWNLOAD_URL EXTRAS=postgresql,tests-es7 SQLALCHEMY_DATABASE_URI=$POSTGRESQL_SQLALCHEMY_DATABASE_URI
    - REQUIREMENTS=release OAREPO_VERSION=3.2.1 ES=$ES7_DOWNLOAD_URL EXTRAS=sqlite,tests-es7

python:
  - "3.7"
  - "3.8"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder pip-tools"
  - "requirements-builder -e $EXTRAS --level=pypi setup.py > .travis-release-requirements.in"
  - "pip-compile -U --verbose -o .travis-release-requirements.txt .travis-release-requirements.in"
  - cat .travis-release-requirements.txt
  - mkdir /tmp/elasticsearch
  - wget -O - $ES | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - "/tmp/elasticsearch/bin/elasticsearch &"
  - sleep 10

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[$EXTRAS]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "Ayb3JqnLiLraokC7AFpZzneN36lRzvVmMWHJaXWty2FhFIi+XRuyitn4wyz8zsQULxznO1Wb20pJTH7MncvVJllYC/mb84Xdo5vBSLzvzg27IUABJZw6HtBbRc71Hgfb6hdSJ7mIYGNXIIT6czHUZ7ICv6z6eP8ysKFfjph81uiTYq2peVfGOY//Ti4vvhKEzNh/lRCdnzq+BnYi6C5VBwz+cdcxRQoZgCh2xjWPm/OR2baZQQEnG8F2fweYoqpvI+WF/H+OSp5L7LIR30d37O4sfAgg24NcrGgac67Pp7s2FBnmQLC3YA1GM/F1TfITiIzkHFQ/nfAqRibY1yOADQ/hJoz3wCr+LaJHoScdlGt5p1caTO6kX4TR36VPrfZzWZCrSnQGVjj/0PtKRAYYuyrbIB4B/nPO8AXcSUeaCEKO+khyv5qxPn2YchcVFI+JPnQz4uK9WEml3MZMKTRSL7gtQ/fssQwjnBZNYWT5XyQBUJMrOycrfrd62JuTTIJAu6lcqFh62rIoAc+vAN7mfHjzLk6/5Z4ZWb/sCMDDVNAPjT4PZEGaC9Diad8203kKBA7KtvTD2Sh5cer8tXQ0ypNsha9u0tPd+BUVFAV9PF7kD99jq7C3capRYQyUiFB3RkcME99Op1T4o3XdQroeG/aLH9BJc/p3EN0r7sLz2gk="
  on:
    tags: true
    branch: master
  distributions: "sdist bdist_wheel"
  skip_existing: true
